image: docker:stable

variables:
  TAG_VERSION_PREFIX: dsilabs/zoom-tiny

stages:
  - build
  - push
  - downstream

build image 3.7:
  stage: build
  script:
    - docker info
    - docker build --no-cache --build-arg BASE_TAG=3.7-latest -t ${TAG_VERSION_PREFIX}:3.7 .
  tags:
    - shell

build image 3.9:
  stage: build
  script:
    - docker info
    - docker build --no-cache --build-arg BASE_TAG=3.9-latest -t ${TAG_VERSION_PREFIX}:3.9 .
  tags:
    - shell

push 3.7:
  stage: push
  only:
    - master
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache --build-arg BASE_TAG=3.7-latest -t ${TAG_VERSION_PREFIX}:3.7-latest .
    - docker push ${TAG_VERSION_PREFIX}:3.7-latest
    - docker tag ${TAG_VERSION_PREFIX}:3.7-latest ${TAG_VERSION_PREFIX}:latest
    - docker push ${TAG_VERSION_PREFIX}:latest
  tags:
    - shell

push 3.9:
  stage: push
  only:
    - master
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache --build-arg BASE_TAG=3.9-latest -t ${TAG_VERSION_PREFIX}:3.9-latest .
    - docker push ${TAG_VERSION_PREFIX}:3.9-latest
  tags:
    - shell

downstream:
  stage: downstream
  trigger:
    project: dsilabs/zoom-cd
  only:
    - master
