
image: docker:stable

variables:
  LATEST_VER: dsilabs/zoom-tiny:latest

stages:
  - Build Image
  - Push to Docker Hub

docker build:
  stage: Build Image
  script:
  - docker info
  - docker build -t $LATEST_VER .
  tags:
  - shell
  
docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $LATEST_VER && docker image rm $LATEST_VER
  tags:
  - shell
