
image: docker:stable

variables:
  IMAGE_PREFIX: dsilabs/zoom-tiny

stages:
  - build
  - publish
  # - downstream

build 3.7:
  stage: build
  variables:
    TAG_NAME: 3.7-latest
  script:
    - docker pull dsilabs/zoom:${TAG_NAME}
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
  tags:
    - shell

build 3.9:
  stage: build
  variables:
    TAG_NAME: 3.9-latest
  script:
    - docker pull dsilabs/zoom:${TAG_NAME}
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
  tags:
    - shell

build 3.12:
  stage: build
  variables:
    TAG_NAME: 3.12-latest
  script:
    - docker pull dsilabs/zoom:${TAG_NAME}
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
  tags:
    - shell

build 3.12 mysql8:
  stage: build
  variables:
    TAG_NAME: 3.12-mysql8-latest
  script:
    - docker pull dsilabs/zoom:3.12-latest
    - docker build --no-cache -f Dockerfile-MySQL8 -t ${IMAGE_PREFIX}:${TAG_NAME} .
  tags:
    - shell

publish 3.7:
  stage: publish
  variables:
    TAG_NAME: 3.7-latest
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
    - docker push ${IMAGE_PREFIX}:${TAG_NAME}
    - docker tag ${IMAGE_PREFIX}:${TAG_NAME} ${IMAGE_PREFIX}:latest
    - docker push ${IMAGE_PREFIX}:latest
  only:
    - master
  tags:
    - shell

publish 3.9:
  stage: publish
  variables:
    TAG_NAME: 3.9-latest
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
    - docker push ${IMAGE_PREFIX}:${TAG_NAME}
  only:
    - master
  tags:
    - shell

publish 3.12:
  stage: publish
  variables:
    TAG_NAME: 3.12-latest
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache --build-arg BASE_TAG=${TAG_NAME} -t ${IMAGE_PREFIX}:${TAG_NAME} .
    - docker push ${IMAGE_PREFIX}:${TAG_NAME}
  only:
    - master
  tags:
    - shell

publish 3.12 mysql8:
  stage: publish
  variables:
    TAG_NAME: 3.12-mysql8-latest
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build --no-cache -f Dockerfile-MySQL8 -t ${IMAGE_PREFIX}:${TAG_NAME} .
    - docker push ${IMAGE_PREFIX}:${TAG_NAME}
  only:
    - master
  tags:
    - shell

downstream:
  stage: downstream
  trigger:
    project: dsilabs/zoom-cd
  only:
    - master
