
image: docker:stable

variables:
  IMAGE_NAME: dsilabs/zoom-tiny:latest

stages:
  - publish
  - downstream

publish image:
  stage: publish
  script:
    - docker info
    - docker pull dsilabs/zoom:latest
    - docker build --no-cache -t $IMAGE_NAME .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $IMAGE_NAME && docker image rm $IMAGE_NAME
  only:
    - master
  tags:
    - shell

publish MySQL 8 image:
  stage: publish
  variables:
    IMAGE_NAME: dsilabs/zoom-tiny-mysql8:latest
  script:
    - docker info
    - docker pull dsilabs/zoom:latest
    - docker build --no-cache -f Dockerfile-MySQL8 -t $IMAGE_NAME .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $IMAGE_NAME && docker image rm $IMAGE_NAME
  only:
    - master
  tags:
    - shell

downstream:
  stage: downstream
  trigger: dsilabs/zoom-cd
  only:
    - master
