
image: docker:stable

variables:
  IMAGE_NAME: dsilabs/zoom-tiny:latest

stages:
  - build
  - publish

build image:
  stage: build
  script:
  - docker info
  - docker build -t $IMAGE_NAME .
  tags:
  - shell

publish image:
  stage: publish
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $IMAGE_NAME && docker image rm $IMAGE_NAME
  tags:
  - shell
