
image: docker:stable

variables:
  IMAGE_NAME: dsilabs/zoom-tiny:latest

stages:
  - publish
  - downstream

publish image:
  stage: publish
  #only:
  #- master
  script:
  - docker info
  - docker build --no-cache -t $IMAGE_NAME .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $IMAGE_NAME && docker image rm $IMAGE_NAME
  tags:
  - shell

downstream:
  stage: downstream
  trigger: dsilabs/zoom-cd
  only:
  - master
